### ISSUE TITLE
[BAZK] Frontend development

### ISSUE THREAD

**Issue by veigajoao** [hack-a-chain-software/bazk#17]
Implement design screens

Screens
- [x] Dashboard
- [x] Ceremony
- [x] Create Ceremony
- [x] Create Contribution

Integrations
- [x] Dashboard
- [x] Ceremony
- [x] Create Ceremony
- [x] Create Contribution

Pod Updates
- [x] Create server
- [x] Lock pod to execute 1 command at a time
- [x] Update command to auto download last contribution

UI
- [x] Create a toast machine

**Design reference**: https://www.figma.com/file/T1if1QoYSkcNBSa55eoHbm/BAZK---website-(LP)?type=design&node-id=497-3802&mode=design&t=BeDy0RPDPtYUnAle-0

**Comment by p-destri** [comment]
wen design ?

**Comment by 1Mateus** [comment]
Figma design for app: https://www.figma.com/file/T1if1QoYSkcNBSa55eoHbm/BAZK---website-(LP)?type=design&node-id=380-8&mode=design&t=BeDy0RPDPtYUnAle-0

**Comment by 1Mateus** [comment]
@bruno-HaC We need o change the behavior when the user will create a new contribution:  https://www.figma.com/file/T1if1QoYSkcNBSa55eoHbm/BAZK---website-(LP)?type=design&node-id=926-13813&mode=design&t=BeDy0RPDPtYUnAle-0

**Comment by 1Mateus** [comment]
- [ ] Fix ghost bar

![Image](https://github.com/hack-a-chain-software/bazk/assets/42101423/17628951-431c-4773-82d8-dd0bcca9ce11)
![Image](https://github.com/hack-a-chain-software/bazk/assets/42101423/f8b083c5-05ab-40f1-8013-9524bc3d40c6)
![Image](https://github.com/hack-a-chain-software/bazk/assets/42101423/9708c96a-7d10-4050-90a3-995316e16169)

**Comment by 1Mateus** [comment]
Updated UI: https://www.figma.com/file/T1if1QoYSkcNBSa55eoHbm/BAZK---website-(LP)?type=design&node-id=926-13813&mode=design&t=gTxAdKeaRJF14jyu-0

**Comment by 1Mateus** [comment]
https://ipfs.io/ipfs/Qma8Xqk65PXoaygKravt3menRAiCDsePgvdMGWo6gckT8B/#/ceremony/finished/?id=1711458286

**Comment by 1Mateus** [comment]
Here is a basic Circuit.json for testing the creation of ceremonies
